Vim: Switch from Vundle to Plug to manage plugins
Switch from gmarik/Vundle.vim to junegunn/vim-plug to manage vim
plugins. Mainly for speed reasons.

In order to do the switch, after getting this commit one should:

- Change all local `Plugin` lines to be `Plug` and adjust the options
to that of Plug.
- Run the following commands from within Vim:

    :PlugUpgrade
    :PlugInstall
    :PlugUpdate
    :PlugClean

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,24 +1,12 @@
 #!/bin/bash
 
 
-## Clone Vundle to manage all plugins
-clone_vundle()
+## Download all vim plug-ins
+get_vim_plugins()
 {
-    [[ -d vim/bundle/vundle/.git ]] &&
-        { echo "Vundle is already installed"; return 0; }
-    git clone git://github.com/gmarik/vundle.git vim/bundle/vundle ||
-        { echo "Could not clone Vundle"; return 1; }
-
-    return 0
-}
-
-
-## Use vundle to download all vim plug-ins
-get_vim_bundles()
-{
-    echo "Updating Vim Bundles"
-    clone_vundle || return 1
-    vim +BundleInstall +qa || (echo "Error installing bundles"; return 1 )
+    echo "Installing Vim Plugins"
+    vim +PlugUpgrade +qa || { echo 'Error upgrading Plug. Will continue.'; }
+    vim +PlugInstall +qa || { echo 'Error installing vim plugins'; return 1 }
 }
 
 ## Run xmodmap with the customisations in ~/.Xmodmap
@@ -30,7 +18,7 @@ apply_xmodmap()
 
 post_install_actions()
 {
-    get_vim_bundles
+    get_vim_plugins
     apply_xmodmap
 }
 
